# Generated by Django 5.1.4 on 2025-01-14 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Progress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField(default=1, max_length=100)),
                ("experience", models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(model_name="address", name="latitude",),
        migrations.RemoveField(model_name="address", name="longitude",),
        migrations.RemoveField(model_name="address", name="postal_code",),
        migrations.RemoveField(model_name="address", name="street",),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[(1, "User"), (2, "Admin")], default=1, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="progress",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.progress",
            ),
        ),
    ]
